shell:
  program: /opt/homebrew/opt/fish/bin/fish
  args:
    - -l
    - -c
    - 'tmux attach || tmux'

font:
  use_thin_strokes: true
  normal:
    family: Cozette
  bold:
    family: Cozette
  italic:
    family: VictorMono Nerd Font
  bold_italic:
    family: VictorMono Nerd Font
  size: 14

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#282c34'
    foreground: '#bbc2cf'
  normal:
    black: '#1B2229'
    red: '#ff6c6b'
    green: '#98be65'
    yellow: '#ECBE7B'
    blue: '#2257A0'
    magenta: '#a9a1e1'
    cyan: '#5699AF'
    white: '#DFDFDF'
  bright:
    black: '#3f444a'
    red: '#da8548'
    green: '#4db5bd'
    yellow: '#ECBE7B'
    blue: '#51afef'
    magenta: '#c678dd'
    cyan: '#46D9FF'
    white: '0xffffff'
